version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.10-management    
    hostname: rabbit10-1-98-75
    container_name: rabbitmq3.10
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./logs:/var/log/rabbitmq
    environment:
      - RABBITMQ_LOGS=
      - RABBITMQ_LOG_BASE=/var/log/rabbitmq
